### ISSUE TITLE
Swipe to go back gesture not working in iOS

### ISSUE THREAD

**Issue by drmaven** [RadekVyM/SimpleToolkit#18]
Hello,

While the swipe to go back gesture works fine in Android, in iOS it's not working at all. 
I am pushing the page like this from within a tab: Shell.Current.GoToAsync("route");

Is there any workaround?

PS. Congrats on this great plugin, it really brings much needed features to Shell.

**Comment by RadekVyM** [comment]
Hi @drmaven,
thanks for finding the missing feature. I tried to implement it in [the newest version of the package](https://www.nuget.org/packages/SimpleToolkit.SimpleShell/2.1.1).

**Comment by drmaven** [comment]
Thanks for the quick response and solution, it works great!

I am wondering, is there a way to keep the default Shell transitions and swipe back gesture?

**Comment by RadekVyM** [comment]
Hi @drmaven,

`SimpleShell` does not support native transitions at all because it is not implemented using native navigation controls. You can create your [own transitions](https://github.com/RadekVyM/SimpleToolkit/blob/main/docs/SimpleToolkit.SimpleShell/Transitions.md), but it is a bit limited. For example, it is not possible to create the aforementioned transition when swiping back on iOS.

I recommend using normal `Shell` for a native look and feel.

**Comment by drmaven** [comment]
That's fine, SimpleShell provides many more benefits that I don't see myself going back to regular Shell. Thanks for the explanation!
